/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Online_Banking_System;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;

/**
 *
 * @author subodh
 */
public class Add_BankAcoount_Page extends javax.swing.JFrame {

    /**
     * Creates new form Add_BankAcoount_Page
     */
    String phonenumber;
    String username,password;
    public Add_BankAcoount_Page() {
        initComponents();
    }
public void getMobile(String mobile){
    phonenumber = mobile;
}

 public void getCred(String us, String pswdd){
        username = us;
       password = pswdd;
        
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel5 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        addbankpanel = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        lblbankname = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        addbankaccountpanel = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        txtsearch = new javax.swing.JTextField();
        lblsearchbankname = new javax.swing.JLabel();
        btnaddbank = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocation(new java.awt.Point(400, 200));
        addWindowFocusListener(new java.awt.event.WindowFocusListener() {
            public void windowGainedFocus(java.awt.event.WindowEvent evt) {
                formWindowGainedFocus(evt);
            }
            public void windowLostFocus(java.awt.event.WindowEvent evt) {
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Add Bank Account");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 10, -1, 20));
        getContentPane().add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, 400, 10));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/bank (1).png"))); // NOI18N
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 80, -1, -1));

        jButton1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jButton1.setText("Add Bank Account");
        jButton1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 150, -1, 20));

        addbankpanel.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        addbankpanel.addContainerListener(new java.awt.event.ContainerAdapter() {
            public void componentAdded(java.awt.event.ContainerEvent evt) {
                addbankpanelComponentAdded(evt);
            }
        });
        addbankpanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/bank (1).png"))); // NOI18N
        addbankpanel.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, -1, -1));

        lblbankname.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        addbankpanel.add(lblbankname, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 10, 80, 20));

        jLabel4.setText("Saving Account");
        addbankpanel.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 40, -1, -1));

        getContentPane().add(addbankpanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 60, 190, 70));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/bank (1).png"))); // NOI18N
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 140, -1, -1));

        jLabel8.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel8.setText("XYZ Bank ");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 80, 80, 20));

        addbankaccountpanel.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        addbankaccountpanel.addContainerListener(new java.awt.event.ContainerAdapter() {
            public void componentAdded(java.awt.event.ContainerEvent evt) {
                addbankaccountpanelComponentAdded(evt);
            }
        });
        addbankaccountpanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setText("Search Bank :");
        addbankaccountpanel.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, -1, 30));

        txtsearch.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtsearchKeyTyped(evt);
            }
        });
        addbankaccountpanel.add(txtsearch, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 10, 130, 30));

        lblsearchbankname.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblsearchbanknameMouseClicked(evt);
            }
        });
        addbankaccountpanel.add(lblsearchbankname, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 60, 200, 20));

        btnaddbank.setText("Add");
        btnaddbank.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnaddbankActionPerformed(evt);
            }
        });
        addbankaccountpanel.add(btnaddbank, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 120, -1, -1));

        getContentPane().add(addbankaccountpanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 200, 350, 190));

        jLabel3.setText("Saving Account");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 100, -1, -1));

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/close_1.png"))); // NOI18N
        jButton2.setBorderPainted(false);
        jButton2.setContentAreaFilled(false);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 10, 20, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtsearchKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtsearchKeyTyped
        // TODO add your handling code here:
        
        try{
            Class.forName("com.mysql.jdbc.Driver");
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/onbanking_system","root","");
            
                    String sql ="select * from bank where BankName LIKE '"+txtsearch.getText()+"%'";
                     PreparedStatement pst = con.prepareStatement(sql);
                     ResultSet rs = pst.executeQuery();
                     while(rs.next()){
                     
                     if(txtsearch.getText()==" "){
               lblsearchbankname.setText(" ");
           }else{
                         lblsearchbankname.setText(rs.getString("BankName"));
                     }
                     
            
                }
           
           
           
        }catch(Exception ex){
            System.out.println(ex.getMessage());
        }
    }//GEN-LAST:event_txtsearchKeyTyped

    private void addbankpanelComponentAdded(java.awt.event.ContainerEvent evt) {//GEN-FIRST:event_addbankpanelComponentAdded
        // TODO add your handling code here:
        addbankpanel.setVisible(false);
    }//GEN-LAST:event_addbankpanelComponentAdded

    private void addbankaccountpanelComponentAdded(java.awt.event.ContainerEvent evt) {//GEN-FIRST:event_addbankaccountpanelComponentAdded
        // TODO add your handling code here:
        addbankaccountpanel.setVisible(false);
    }//GEN-LAST:event_addbankaccountpanelComponentAdded

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        addbankaccountpanel.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void btnaddbankActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnaddbankActionPerformed
        // TODO add your handling code here:
         try{
             
             
            Class.forName("com.mysql.jdbc.Driver");
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/onbanking_system","root","");
            
                    String sql ="select * from bank where MobileNumber='"+phonenumber+"' and BankName ='"+txtsearch.getText()+"'";
                     PreparedStatement pst = con.prepareStatement(sql);
                     ResultSet rs = pst.executeQuery();
                     if(rs.next()){
                       String Bank = rs.getString("BankName");
                       String sql2="insert into added_bank(Bank_Name,Mobile_Number,Amount) values('"+rs.getString("BankName")+"','"+rs.getString("MobileNumber")+"','"+rs.getString("Amount")+"')";
                       PreparedStatement pst2 = con.prepareStatement(sql2);
                       int i=pst2.executeUpdate();
                       if(i>0){
                           JOptionPane.showMessageDialog(null, "Bank Added Succesfully");
                       }
                       addbankpanel.setVisible(true);
                        lblbankname.setText(Bank);
                       
                     }else{
                         JOptionPane.showMessageDialog(null, "This Bank is not linked to \n your mobile Number");
                     }
           
        }catch(Exception ex){
            System.out.println(ex.getMessage());
        }
       
        
        
    }//GEN-LAST:event_btnaddbankActionPerformed

    private void formWindowGainedFocus(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowGainedFocus
        // TODO add your handling code here:
       
    }//GEN-LAST:event_formWindowGainedFocus

    private void lblsearchbanknameMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblsearchbanknameMouseClicked
        // TODO add your handling code here:
        String bname = lblsearchbankname.getText();
        txtsearch.setText(bname);
    }//GEN-LAST:event_lblsearchbanknameMouseClicked

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        Login_Page lp = new Login_Page();
        lp.getCredential(username, password);
        lp.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Add_BankAcoount_Page.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Add_BankAcoount_Page.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Add_BankAcoount_Page.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Add_BankAcoount_Page.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Add_BankAcoount_Page().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel addbankaccountpanel;
    private javax.swing.JPanel addbankpanel;
    private javax.swing.JButton btnaddbank;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel lblbankname;
    private javax.swing.JLabel lblsearchbankname;
    private javax.swing.JTextField txtsearch;
    // End of variables declaration//GEN-END:variables
}
