/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Online_Banking_System;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author subodh
 */
public class Admin_Page extends javax.swing.JFrame {

    
    public Admin_Page() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtadminusername = new javax.swing.JTextField();
        txtadminpassword = new javax.swing.JPasswordField();
        btnadminlogin = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        btnadmingoback = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocation(new java.awt.Point(500, 200));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/bank (1).png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 0, 30, 50));

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Admin Login");
        jLabel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 20, 80, 20));

        jLabel3.setText("password");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 150, -1, -1));

        jLabel4.setText("username");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 110, -1, -1));
        getContentPane().add(txtadminusername, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 110, 120, -1));
        getContentPane().add(txtadminpassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 150, 120, -1));

        btnadminlogin.setText("Login");
        btnadminlogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnadminloginActionPerformed(evt);
            }
        });
        getContentPane().add(btnadminlogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 200, -1, -1));
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 130, 20, -1));
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 280, 50, -1));
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 130, 10, -1));

        btnadmingoback.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/icons8-go-back-30.png"))); // NOI18N
        btnadmingoback.setBorderPainted(false);
        btnadmingoback.setContentAreaFilled(false);
        btnadmingoback.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnadmingobackActionPerformed(evt);
            }
        });
        getContentPane().add(btnadmingoback, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 40, 30));
        getContentPane().add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 60, 400, 10));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnadmingobackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnadmingobackActionPerformed
        // TODO add your handling code here:
        Login_Page lp  = new Login_Page();
        lp.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnadmingobackActionPerformed

    private void btnadminloginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnadminloginActionPerformed
        String pass = new String(txtadminpassword.getPassword());
        try {
            // TODO add your handling code here:
            Class.forName("com.mysql.jdbc.Driver");
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/onbanking_system","root","");
            String sql = "select *from admin where username='"+txtadminusername.getText()+"' and password='"+pass+"'";
            PreparedStatement pst = con.prepareStatement(sql);
            ResultSet rs  = pst.executeQuery();
            while(rs.next()){
                JOptionPane.showMessageDialog(null, "Login Succesfully");
                Admin_Page2 ap = new Admin_Page2();
                ap.setVisible(true);
                this.dispose();
            }
            
            
        } catch (Exception ex) {
           
        }
        
    }//GEN-LAST:event_btnadminloginActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Admin_Page.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Admin_Page.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Admin_Page.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Admin_Page.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Admin_Page().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnadmingoback;
    private javax.swing.JButton btnadminlogin;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JPasswordField txtadminpassword;
    private javax.swing.JTextField txtadminusername;
    // End of variables declaration//GEN-END:variables
}
