/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Online_Banking_System;

import java.awt.Color;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.util.Random;
import javax.swing.JOptionPane;

/**
 *
 * @author subodh
 */
public class Bank_Transfer_Page extends javax.swing.JFrame {

    /**
     * Creates new form Bank_Transfer_Page
     */
    String recptname;
    String sendername,upiid,amount,pusername,pass,upitextamount,PhoneNumber;
    
     public void getData(String name,String balance,String username,String password){
         sendername = name;
         amount = balance;
         pusername = username;
         pass = password;
     }
    public Bank_Transfer_Page() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        txtaccountnumber = new javax.swing.JTextField();
        txtreenteraccountnumber = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtifsccode = new javax.swing.JTextField();
        txtreceipentname = new javax.swing.JTextField();
        btnconfirm = new javax.swing.JButton();
        paypanel = new javax.swing.JPanel();
        txtamount = new javax.swing.JTextField();
        btnpay = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocation(new java.awt.Point(400, 200));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Enter Receipent Details");
        jLabel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 10, -1, -1));
        getContentPane().add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 50, 400, 10));

        txtaccountnumber.setForeground(new java.awt.Color(153, 153, 153));
        txtaccountnumber.setText("Account Number");
        txtaccountnumber.addContainerListener(new java.awt.event.ContainerAdapter() {
            public void componentAdded(java.awt.event.ContainerEvent evt) {
                txtaccountnumberComponentAdded(evt);
            }
        });
        txtaccountnumber.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtaccountnumberFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtaccountnumberFocusLost(evt);
            }
        });
        getContentPane().add(txtaccountnumber, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 70, 190, 30));

        txtreenteraccountnumber.setForeground(new java.awt.Color(153, 153, 153));
        txtreenteraccountnumber.setText("Re Enter Account Number");
        txtreenteraccountnumber.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtreenteraccountnumberFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtreenteraccountnumberFocusLost(evt);
            }
        });
        txtreenteraccountnumber.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtreenteraccountnumberActionPerformed(evt);
            }
        });
        getContentPane().add(txtreenteraccountnumber, new org.netbeans.lib.awtextra.AbsoluteConstraints(69, 120, 190, 30));
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 410, 60, 10));

        txtifsccode.setForeground(new java.awt.Color(153, 153, 153));
        txtifsccode.setText("IFSC CODE");
        txtifsccode.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtifsccodeFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtifsccodeFocusLost(evt);
            }
        });
        getContentPane().add(txtifsccode, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 170, 190, 30));

        txtreceipentname.setForeground(new java.awt.Color(153, 153, 153));
        txtreceipentname.setText("Receipent Name");
        txtreceipentname.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtreceipentnameFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtreceipentnameFocusLost(evt);
            }
        });
        getContentPane().add(txtreceipentname, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 220, 190, 30));

        btnconfirm.setText("Confirm");
        btnconfirm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnconfirmActionPerformed(evt);
            }
        });
        getContentPane().add(btnconfirm, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 270, -1, -1));

        paypanel.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        paypanel.addContainerListener(new java.awt.event.ContainerAdapter() {
            public void componentAdded(java.awt.event.ContainerEvent evt) {
                paypanelComponentAdded(evt);
            }
        });
        paypanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtamount.setForeground(new java.awt.Color(153, 153, 153));
        txtamount.setText("Enter Amount");
        txtamount.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtamountFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtamountFocusLost(evt);
            }
        });
        paypanel.add(txtamount, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 10, 90, 30));

        btnpay.setText("Pay");
        btnpay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnpayActionPerformed(evt);
            }
        });
        paypanel.add(btnpay, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 60, -1, -1));

        getContentPane().add(paypanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 310, 180, 100));

        jButton1.setText("search IFSC");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 170, 100, -1));

        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/close_1.png"))); // NOI18N
        jButton3.setBorderPainted(false);
        jButton3.setContentAreaFilled(false);
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 10, 20, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtaccountnumberComponentAdded(java.awt.event.ContainerEvent evt) {//GEN-FIRST:event_txtaccountnumberComponentAdded
        // TODO add your handling code here:
       
    }//GEN-LAST:event_txtaccountnumberComponentAdded

    private void txtaccountnumberFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtaccountnumberFocusGained
        // TODO add your handling code here:
        if(txtaccountnumber.getText().equals("Account Number")){
            txtaccountnumber.setText("");
            txtaccountnumber.setForeground(new Color(0, 0, 0));
        }
    }//GEN-LAST:event_txtaccountnumberFocusGained

    private void txtaccountnumberFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtaccountnumberFocusLost
        // TODO add your handling code here:
         if(txtaccountnumber.getText().equals("")){
            txtaccountnumber.setText("Account Number");
            txtaccountnumber.setForeground(new Color(153, 153, 153));
        }
    }//GEN-LAST:event_txtaccountnumberFocusLost

    private void txtreenteraccountnumberFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtreenteraccountnumberFocusGained
        // TODO add your handling code here:
        if(txtreenteraccountnumber.getText().equals("Re Enter Account Number")){
            txtreenteraccountnumber.setText("");
            txtreenteraccountnumber.setForeground(new Color(0, 0, 0));
        }
    }//GEN-LAST:event_txtreenteraccountnumberFocusGained

    private void txtreenteraccountnumberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtreenteraccountnumberActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtreenteraccountnumberActionPerformed

    private void txtreenteraccountnumberFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtreenteraccountnumberFocusLost
        // TODO add your handling code here:
         if(txtreenteraccountnumber.getText().equals("")){
            txtreenteraccountnumber.setText("Re Enter Account Number");
            txtreenteraccountnumber.setForeground(new Color(153, 153, 153));
        }
          if(txtaccountnumber.getText().equals(txtreenteraccountnumber.getText())){
         }else{
            JOptionPane.showMessageDialog(null,"Account Number \n Not Match");
        }
    }//GEN-LAST:event_txtreenteraccountnumberFocusLost

    private void txtifsccodeFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtifsccodeFocusGained
        // TODO add your handling code here:
        if(txtifsccode.getText().equals("IFSC CODE")){
            txtifsccode.setText("");
            txtifsccode.setForeground(new Color(0, 0, 0));
        }
    }//GEN-LAST:event_txtifsccodeFocusGained

    private void txtifsccodeFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtifsccodeFocusLost
        // TODO add your handling code here:
        if(txtifsccode.getText().equals("")){
            txtifsccode.setText("IFSC CODE");
            txtifsccode.setForeground(new Color(153, 153, 153));
        }
    }//GEN-LAST:event_txtifsccodeFocusLost

    private void txtreceipentnameFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtreceipentnameFocusGained
        // TODO add your handling code here:
         if(txtreceipentname.getText().equals("Receipent Name")){
            txtreceipentname.setText("");
            txtreceipentname.setForeground(new Color(0, 0, 0));
        }
    }//GEN-LAST:event_txtreceipentnameFocusGained

    private void txtreceipentnameFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtreceipentnameFocusLost
        // TODO add your handling code here:
         if(txtreceipentname.getText().equals("")){
            txtreceipentname.setText("Receipent Name");
            txtreceipentname.setForeground(new Color(153, 153, 153));
        }
    }//GEN-LAST:event_txtreceipentnameFocusLost

    private void txtamountFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtamountFocusGained
        // TODO add your handling code here:
        if(txtamount.getText().equals("Enter Amount")){
            txtamount.setText("");
            txtamount.setForeground(new Color(0, 0, 0));
        }
    }//GEN-LAST:event_txtamountFocusGained

    private void txtamountFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtamountFocusLost
        // TODO add your handling code here:
         if(txtamount.getText().equals("")){
            txtamount.setText("Enter Amount");
            txtamount.setForeground(new Color(153, 153, 153));
        }
    }//GEN-LAST:event_txtamountFocusLost

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
       
            try{
                Class.forName("com.mysql.jdbc.Driver");
                Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/onbanking_system","root","");
                String sql = "select * from bank_data where Acc_Number='"+txtreenteraccountnumber.getText()+"'";
                PreparedStatement pst = con.prepareStatement(sql);
                ResultSet rs = pst.executeQuery();
                while(rs.next()){
                    txtifsccode.setText(rs.getString("IFSC"));
                    txtifsccode.setForeground(new Color(0, 0, 0));
                    txtreceipentname.setText(rs.getString("Receipent_Name"));
                    txtreceipentname.setForeground(new Color(0, 0, 0));
                }
                
            }catch(Exception ex){
                System.out.println(ex.getMessage());
            }
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void paypanelComponentAdded(java.awt.event.ContainerEvent evt) {//GEN-FIRST:event_paypanelComponentAdded
        // TODO add your handling code here:
        paypanel.setVisible(false);
    }//GEN-LAST:event_paypanelComponentAdded

    private void btnconfirmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnconfirmActionPerformed
        // TODO add your handling code here:
        recptname = txtreceipentname.getText();
        try{
                Class.forName("com.mysql.jdbc.Driver");
                Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/onbanking_system","root","");
                String sql = "select * from bank_data where Acc_Number='"+txtreenteraccountnumber.getText()+"'";
                PreparedStatement pst = con.prepareStatement(sql);
                ResultSet rs = pst.executeQuery();
                while(rs.next()){
                   paypanel.setVisible(true);
                }
                
            }catch(Exception ex){
                System.out.println(ex.getMessage());
            }
    }//GEN-LAST:event_btnconfirmActionPerformed

    private void btnpayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnpayActionPerformed
        // TODO add your handling code here:
       String btamount  = txtamount.getText();
        int payamount  = Integer.parseInt(btamount);
         int parentamount = Integer.parseInt(amount);
        int rembal = parentamount-payamount;
        

        String rembalance = ""+rembal;
        if(payamount<parentamount){
             try{
            Class.forName("com.mysql.jdbc.Driver");
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/onbanking_system","root","");
            String sql = "update userdetails set Amount='"+rembalance+"' where username='"+pusername+"' and password='"+pass+"'";
             PreparedStatement pst = con.prepareStatement(sql);
            int i=pst.executeUpdate();
            if(i>0){
            }
              Random rnd = new Random();
               int num = rnd.nextInt(999999);
              String transaction = String.format("%012d", num);
              
               String sql2 = "insert into transactions(Transaction_ID,Too,Fromm,Amount)values('"+transaction+"','"+recptname+"','"+sendername+"','"+btamount+"')";
                   PreparedStatement pst2 = con.prepareStatement(sql2);
                  int j=pst2.executeUpdate();
             
             if(j>0){
                 JOptionPane.showMessageDialog(null,"Pay Succesfully");
                 paypanel.setVisible(false);
                 
             }
              
           }catch(Exception ex){
              System.out.println(ex.getMessage());
           }
        }
        
    }//GEN-LAST:event_btnpayActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        Login_Page lp = new Login_Page();
        lp.getCredential(pusername, pass);
        lp.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Bank_Transfer_Page.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Bank_Transfer_Page.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Bank_Transfer_Page.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Bank_Transfer_Page.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Bank_Transfer_Page().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnconfirm;
    private javax.swing.JButton btnpay;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JPanel paypanel;
    private javax.swing.JTextField txtaccountnumber;
    private javax.swing.JTextField txtamount;
    private javax.swing.JTextField txtifsccode;
    private javax.swing.JTextField txtreceipentname;
    private javax.swing.JTextField txtreenteraccountnumber;
    // End of variables declaration//GEN-END:variables
}
