/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Online_Banking_System;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.util.Random;
import javax.swing.JOptionPane;

/**
 *
 * @author subodh
 */
public class Pay_to_UPI extends javax.swing.JFrame {

    /**
     * Creates new form Pay_to_UPI
     */
    int payamount,parentamount;
    public Pay_to_UPI() {
        initComponents();
    }
    String sendername,upiid,amount,pusername,pass,upitextamount,timestamp;
    
     public void getData(String name,String balance,String username,String password){
         sendername = name;
         amount = balance;
         pusername = username;
         pass = password;
     }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        enterupiidpanel = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        txtupiid = new javax.swing.JTextField();
        btnupicontinue = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        paypanel = new javax.swing.JPanel();
        txtupiamount = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        btnpay = new javax.swing.JButton();
        lblsendto = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocation(new java.awt.Point(400, 200));
        addWindowFocusListener(new java.awt.event.WindowFocusListener() {
            public void windowGainedFocus(java.awt.event.WindowEvent evt) {
                formWindowGainedFocus(evt);
            }
            public void windowLostFocus(java.awt.event.WindowEvent evt) {
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Pay To UPI ID");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 10, -1, -1));
        getContentPane().add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, 400, -1));

        enterupiidpanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setText("Enter UPI ID :-");
        enterupiidpanel.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, -1, -1));

        txtupiid.setToolTipText("Enter UPI ID");
        enterupiidpanel.add(txtupiid, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 20, 140, 30));

        btnupicontinue.setText("Continue");
        btnupicontinue.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnupicontinueActionPerformed(evt);
            }
        });
        enterupiidpanel.add(btnupicontinue, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 70, -1, -1));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/output-onlinepngtools.png"))); // NOI18N
        jLabel6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel6MouseClicked(evt);
            }
        });
        enterupiidpanel.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 20, 20, 30));

        getContentPane().add(enterupiidpanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, 290, 120));

        paypanel.addContainerListener(new java.awt.event.ContainerAdapter() {
            public void componentAdded(java.awt.event.ContainerEvent evt) {
                paypanelComponentAdded(evt);
            }
        });
        paypanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        paypanel.add(txtupiamount, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 60, 80, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        jLabel5.setText("Enter Amount ");
        paypanel.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 60, -1, -1));

        btnpay.setText("Pay");
        btnpay.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                btnpayMouseReleased(evt);
            }
        });
        btnpay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnpayActionPerformed(evt);
            }
        });
        paypanel.add(btnpay, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 100, -1, -1));

        lblsendto.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        paypanel.add(lblsendto, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 20, 260, 20));

        getContentPane().add(paypanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 150, 330, 140));

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/icons8-macos-close-30.png"))); // NOI18N
        jButton1.setBorder(null);
        jButton1.setBorderPainted(false);
        jButton1.setContentAreaFilled(false);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 10, 40, 30));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/upi (1).png"))); // NOI18N
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 40));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void paypanelComponentAdded(java.awt.event.ContainerEvent evt) {//GEN-FIRST:event_paypanelComponentAdded
        // TODO add your handling code here:
        paypanel.setVisible(false);
    }//GEN-LAST:event_paypanelComponentAdded

    private void btnupicontinueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnupicontinueActionPerformed
        // TODO add your handling code here:
         upiid = txtupiid.getText();
         
        
        try{
            Class.forName("com.mysql.jdbc.Driver");
            Connection con =  DriverManager.getConnection("jdbc:mysql://localhost:3306/onbanking_system", "root", "");
            String sql = "select * from upi_ids where upi_id='"+upiid+"'";
            PreparedStatement pst = con.prepareStatement(sql);
            ResultSet rs = pst.executeQuery();
            if(rs.next()){
                enterupiidpanel.setVisible(false);
                paypanel.setVisible(true);
                lblsendto.setText("Paying to "+upiid);
                
            }else{
                JOptionPane.showMessageDialog(null,"Enter valid upi id");
            }
        }catch(Exception ex){
            System.out.println(ex.getMessage());
        }
       
       
      
    }//GEN-LAST:event_btnupicontinueActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        Login_Page lp = new Login_Page();
        lp.getCredential(pusername, pass);
        lp.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jLabel6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel6MouseClicked
        // TODO add your handling code here:
        txtupiid.setText(" ");
    }//GEN-LAST:event_jLabel6MouseClicked

    private void btnpayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnpayActionPerformed
        // TODO add your handling code here:
         upitextamount = txtupiamount.getText();
         payamount  = Integer.parseInt(upitextamount);
         parentamount = Integer.parseInt(amount);
        int rembal = parentamount-payamount;
        

        String rembalance = ""+rembal;
        if(payamount<parentamount){
             try{
            Class.forName("com.mysql.jdbc.Driver");
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/onbanking_system","root","");
            String sql = "update userdetails set Amount='"+rembalance+"' where username='"+pusername+"' and password='"+pass+"'";
             PreparedStatement pst = con.prepareStatement(sql);
            int i=pst.executeUpdate();
            if(i>0){
            }
              Random rnd = new Random();
               int num = rnd.nextInt(999999);
              String transaction = String.format("%012d", num);
              
               String sql2 = "insert into transactions(Transaction_ID,Too,Fromm,Amount)values('"+transaction+"','"+upiid+"','"+sendername+"','"+upitextamount+"')";
                   PreparedStatement pst2 = con.prepareStatement(sql2);
                  int j=pst2.executeUpdate();
             
             if(j>0){
                 JOptionPane.showMessageDialog(null,"Pay Succesfully");
                 paypanel.setVisible(false);
                 enterupiidpanel.setVisible(true);
             }
              
           }catch(Exception ex){
              System.out.println(ex.getMessage());
           }
            
        }else{
          JOptionPane.showMessageDialog(null, "Insuffiecient Balance");
        }
        
    }//GEN-LAST:event_btnpayActionPerformed

    private void formWindowGainedFocus(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowGainedFocus
        // TODO add your handling code here:
        
    }//GEN-LAST:event_formWindowGainedFocus

    private void btnpayMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnpayMouseReleased
        // TODO add your handling code here:
//        Random rnd = new Random();
//               int num = rnd.nextInt(999999);
//              String transaction = String.format("%012d", num);
//              
//               
//               try{
//                    Class.forName("com.mysql.jdbc.Driver");
//                    Connection conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/onbanking_system","root","");
//                   String sql2 = "insert into transactions(Transaction_ID,Too,Fromm,Amount)values('"+transaction+"','"+upiid+"','"+sendername+"','"+upitextamount+"')";
//                   PreparedStatement pst2 = conn.prepareStatement(sql2);
//                  int i=pst2.executeUpdate();
//             
//             if(i>0){
//                 JOptionPane.showMessageDialog(null,"Pay Succesfully");
//                 paypanel.setVisible(false);
//                 enterupiidpanel.setVisible(true);
//             }
//                    
//                   
//              }catch(Exception ex){
//                   System.out.println(ex.getMessage());
//              }
    }//GEN-LAST:event_btnpayMouseReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Pay_to_UPI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Pay_to_UPI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Pay_to_UPI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Pay_to_UPI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Pay_to_UPI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnpay;
    private javax.swing.JButton btnupicontinue;
    private javax.swing.JPanel enterupiidpanel;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel lblsendto;
    private javax.swing.JPanel paypanel;
    private javax.swing.JTextField txtupiamount;
    private javax.swing.JTextField txtupiid;
    // End of variables declaration//GEN-END:variables
}
