/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Online_Banking_System;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author subodh
 */
public class Profile_Page extends javax.swing.JFrame {

    /**
     * Creates new form Profile_Page
     */
    String username,password;
    public Profile_Page() {
        
        initComponents();
        
    }
     public void getUsername(String name,String pass){
              username = name;
              password = pass;
          }
    
     
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        profileheading = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        lblpname = new javax.swing.JLabel();
        lblpemail = new javax.swing.JLabel();
        lblpmobile = new javax.swing.JLabel();
        lblpaddress = new javax.swing.JLabel();
        lblpgender = new javax.swing.JLabel();
        lblpaccountnumber = new javax.swing.JLabel();
        lblpbankname = new javax.swing.JLabel();
        lblpifsccode = new javax.swing.JLabel();
        lblpdob = new javax.swing.JLabel();
        lblpusername = new javax.swing.JLabel();
        lblprofilephoto = new javax.swing.JButton();
        lblprofilebackbutton = new javax.swing.JLabel();
        pbottom = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocation(new java.awt.Point(400, 200));
        addContainerListener(new java.awt.event.ContainerAdapter() {
            public void componentAdded(java.awt.event.ContainerEvent evt) {
                formComponentAdded(evt);
            }
        });
        addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                formFocusGained(evt);
            }
        });
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                formMouseClicked(evt);
            }
        });
        addWindowFocusListener(new java.awt.event.WindowFocusListener() {
            public void windowGainedFocus(java.awt.event.WindowEvent evt) {
                formWindowGainedFocus(evt);
            }
            public void windowLostFocus(java.awt.event.WindowEvent evt) {
            }
        });
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        profileheading.setFont(new java.awt.Font("Times New Roman", 1, 15)); // NOI18N
        profileheading.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        profileheading.setText("Profile");
        getContentPane().add(profileheading, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 10, 50, -1));
        getContentPane().add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, 400, 30));

        lblpname.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        getContentPane().add(lblpname, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 60, 300, 20));

        lblpemail.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        getContentPane().add(lblpemail, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 90, 300, 20));

        lblpmobile.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        getContentPane().add(lblpmobile, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 120, 300, 20));

        lblpaddress.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        getContentPane().add(lblpaddress, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 150, 300, 20));

        lblpgender.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        getContentPane().add(lblpgender, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 180, 300, 20));

        lblpaccountnumber.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        getContentPane().add(lblpaccountnumber, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 210, 300, 20));

        lblpbankname.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        getContentPane().add(lblpbankname, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 240, 300, 20));

        lblpifsccode.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        getContentPane().add(lblpifsccode, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 270, 300, 20));

        lblpdob.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        getContentPane().add(lblpdob, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 300, 300, 20));

        lblpusername.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        getContentPane().add(lblpusername, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 330, 300, 20));

        lblprofilephoto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/close_1.png"))); // NOI18N
        lblprofilephoto.setBorderPainted(false);
        lblprofilephoto.setContentAreaFilled(false);
        lblprofilephoto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lblprofilephotoActionPerformed(evt);
            }
        });
        getContentPane().add(lblprofilephoto, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 0, 30, 30));

        lblprofilebackbutton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/profile_img.png"))); // NOI18N
        getContentPane().add(lblprofilebackbutton, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 30, 40));

        pbottom.setFont(new java.awt.Font("Times New Roman", 0, 10)); // NOI18N
        getContentPane().add(pbottom, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 370, 50, 20));
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 380, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowGainedFocus(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowGainedFocus
          try{
        Class.forName("com.mysql.jdbc.Driver");
        Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/onbanking_system","root","");
        String sql = "select *from userdetails where username='"+username+"' and password='"+password+"'";
        PreparedStatement pst = con.prepareStatement(sql);
        ResultSet rs  = pst.executeQuery();
        while(rs.next()){
           String name = rs.getString("uname");
           String email = rs.getString("uemail");
           String mobile = rs.getString("umobile");
           String add = rs.getString("uaddress");
           String gender = rs.getString("ugender");
           String accno = rs.getString("AccountNumber");
           String bankname = rs.getString("BankName");
           String ifsc = rs.getString("IFSCCode");
           String dob = rs.getString("dob");
           
           lblpname.setText("Name :"+"                        "+name);
           lblpemail.setText("Email Id :"+"                    "+email);
           lblpmobile.setText("Mobile No.:"+"               "+mobile);
           lblpaddress.setText("Address :"+"                   "+add);
           lblpgender.setText("Gender :"+"                     "+gender);
           lblpaccountnumber.setText("Account Number :"+"     "+accno);
           lblpbankname.setText("Bank Name :"+"              "+bankname);
           lblpifsccode.setText("IFSC Code :"+"               "+ifsc);
           lblpdob.setText("DOB :"+"                        "+dob);
           lblpusername.setText("Username :"+"                 "+username);
          
        
        }
        }catch(Exception ex){
            System.out.println(ex.getMessage());
        }
        
       
    }//GEN-LAST:event_formWindowGainedFocus

    private void formFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_formFocusGained
        // TODO add your handling code here:
       
    }//GEN-LAST:event_formFocusGained

    private void formMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseClicked
        // TODO add your handling code here:
        
    }//GEN-LAST:event_formMouseClicked

    private void formComponentAdded(java.awt.event.ContainerEvent evt) {//GEN-FIRST:event_formComponentAdded
        // TODO add your handling code here:
       
    }//GEN-LAST:event_formComponentAdded

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        // TODO add your handling code here:
        
    }//GEN-LAST:event_formWindowActivated

    private void lblprofilephotoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lblprofilephotoActionPerformed
        // TODO add your handling code here:
        Login_Page lp = new Login_Page();
        lp.setVisible(true);
        lp.getCredential(username,password);
        this.dispose();
    }//GEN-LAST:event_lblprofilephotoActionPerformed

    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Profile_Page.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Profile_Page.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Profile_Page.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Profile_Page.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Profile_Page().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel lblpaccountnumber;
    private javax.swing.JLabel lblpaddress;
    private javax.swing.JLabel lblpbankname;
    private javax.swing.JLabel lblpdob;
    private javax.swing.JLabel lblpemail;
    private javax.swing.JLabel lblpgender;
    private javax.swing.JLabel lblpifsccode;
    private javax.swing.JLabel lblpmobile;
    private javax.swing.JLabel lblpname;
    private javax.swing.JLabel lblprofilebackbutton;
    private javax.swing.JButton lblprofilephoto;
    private javax.swing.JLabel lblpusername;
    private javax.swing.JLabel pbottom;
    private javax.swing.JLabel profileheading;
    // End of variables declaration//GEN-END:variables
}
