/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Online_Banking_System;

import java.awt.Color;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.util.Random;
import javax.swing.JOptionPane;
import javax.swing.table.TableModel;
import net.proteanit.sql.DbUtils;

/**
 *
 * @author subodh
 */
public class Self_Transfer_Page extends javax.swing.JFrame {

    /**
     * Creates new form Self_Transfer_Page
     */
     String sendername,upiid,amount,pusername,pass,upitextamount;
    int rembal,rd2amount,finalamount;
     public void getData(String name,String balance,String username,String password){
         sendername = name;
         amount = balance;
         pusername = username;
         pass = password;
     }
    public Self_Transfer_Page() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        lbltransfer2 = new javax.swing.JLabel();
        rd1_transfer_to_bankname = new javax.swing.JRadioButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        to_table = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();
        rd2_transfer_to_bankname = new javax.swing.JRadioButton();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel4 = new javax.swing.JLabel();
        rd1_transfer_from_bankname = new javax.swing.JRadioButton();
        rd2_transfer_from_bankname = new javax.swing.JRadioButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        from_table = new javax.swing.JTable();
        jSeparator3 = new javax.swing.JSeparator();
        btnselfcontinue = new javax.swing.JButton();
        selfpanel = new javax.swing.JPanel();
        txtselfamount = new javax.swing.JTextField();
        btnselfpay = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocation(new java.awt.Point(400, 200));
        addWindowFocusListener(new java.awt.event.WindowFocusListener() {
            public void windowGainedFocus(java.awt.event.WindowEvent evt) {
                formWindowGainedFocus(evt);
            }
            public void windowLostFocus(java.awt.event.WindowEvent evt) {
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel1.setText("Self Transfer");
        jLabel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 10, -1, -1));
        getContentPane().add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, 400, -1));

        lbltransfer2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lbltransfer2.setText("Select bank account to transfer to");
        getContentPane().add(lbltransfer2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 160, -1, -1));

        rd1_transfer_to_bankname.setText("XYZ BANK");
        rd1_transfer_to_bankname.addContainerListener(new java.awt.event.ContainerAdapter() {
            public void componentAdded(java.awt.event.ContainerEvent evt) {
                rd1_transfer_to_banknameComponentAdded(evt);
            }
        });
        rd1_transfer_to_bankname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rd1_transfer_to_banknameActionPerformed(evt);
            }
        });
        getContentPane().add(rd1_transfer_to_bankname, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 180, 90, -1));

        to_table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        to_table.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                to_tableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(to_table);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 180, 110, 50));
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 370, 40, 20));

        rd2_transfer_to_bankname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rd2_transfer_to_banknameActionPerformed(evt);
            }
        });
        getContentPane().add(rd2_transfer_to_bankname, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 200, -1, -1));
        getContentPane().add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 150, 400, 10));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel4.setText("Select bank account to transfer from");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, -1, -1));

        rd1_transfer_from_bankname.setText("XYZ BANK");
        rd1_transfer_from_bankname.addContainerListener(new java.awt.event.ContainerAdapter() {
            public void componentAdded(java.awt.event.ContainerEvent evt) {
                rd1_transfer_from_banknameComponentAdded(evt);
            }
        });
        rd1_transfer_from_bankname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rd1_transfer_from_banknameActionPerformed(evt);
            }
        });
        getContentPane().add(rd1_transfer_from_bankname, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 80, 90, -1));

        rd2_transfer_from_bankname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rd2_transfer_from_banknameActionPerformed(evt);
            }
        });
        getContentPane().add(rd2_transfer_from_bankname, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 100, -1, -1));

        from_table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        from_table.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                from_tableMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(from_table);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 80, 110, 50));
        getContentPane().add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 248, 400, 10));

        btnselfcontinue.setText("Continue");
        btnselfcontinue.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnselfcontinueActionPerformed(evt);
            }
        });
        getContentPane().add(btnselfcontinue, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 260, -1, -1));

        selfpanel.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        selfpanel.addContainerListener(new java.awt.event.ContainerAdapter() {
            public void componentAdded(java.awt.event.ContainerEvent evt) {
                selfpanelComponentAdded(evt);
            }
        });
        selfpanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtselfamount.setForeground(new java.awt.Color(153, 153, 153));
        txtselfamount.setText("Enter Amount");
        txtselfamount.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtselfamountFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtselfamountFocusLost(evt);
            }
        });
        selfpanel.add(txtselfamount, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 10, 90, 30));

        btnselfpay.setText("Pay");
        btnselfpay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnselfpayActionPerformed(evt);
            }
        });
        selfpanel.add(btnselfpay, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 60, -1, -1));

        getContentPane().add(selfpanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 290, 200, 100));

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/close_1.png"))); // NOI18N
        jButton1.setBorderPainted(false);
        jButton1.setContentAreaFilled(false);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 10, 30, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void rd1_transfer_to_banknameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rd1_transfer_to_banknameActionPerformed
        // TODO add your handling code here:
        if(rd1_transfer_to_bankname.isSelected()){
        rd2_transfer_to_bankname.setSelected(false);
        }
    }//GEN-LAST:event_rd1_transfer_to_banknameActionPerformed

    private void formWindowGainedFocus(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowGainedFocus
        // TODO add your handling code here:
        try{
             Class.forName("com.mysql.jdbc.Driver");
             Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/onbanking_system","root","");
            String sql = "select Bank_Name from added_bank";
            PreparedStatement pst = con.prepareStatement(sql);
            PreparedStatement pst2 = con.prepareStatement(sql);
            ResultSet rs= pst.executeQuery();
            ResultSet rs2= pst2.executeQuery();
            to_table.setModel(DbUtils.resultSetToTableModel(rs2));
            from_table.setModel(DbUtils.resultSetToTableModel(rs));
        }
        catch(Exception ex){
            System.out.println(ex.getMessage());
        }
    }//GEN-LAST:event_formWindowGainedFocus

    private void to_tableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_to_tableMouseClicked
        // TODO add your handling code here:
         TableModel model=to_table.getModel();
        int row =to_table.getSelectedRow();
        String bankname=(String)model.getValueAt(row,0);
        rd2_transfer_to_bankname.setText(bankname);
        rd2_transfer_to_bankname.setSelected(true);
        rd1_transfer_to_bankname.setSelected(false);
        
    }//GEN-LAST:event_to_tableMouseClicked

    private void rd1_transfer_to_banknameComponentAdded(java.awt.event.ContainerEvent evt) {//GEN-FIRST:event_rd1_transfer_to_banknameComponentAdded
        // TODO add your handling code here:
        
    }//GEN-LAST:event_rd1_transfer_to_banknameComponentAdded

    private void rd2_transfer_to_banknameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rd2_transfer_to_banknameActionPerformed
        // TODO add your handling code here:
         if(rd2_transfer_to_bankname.isSelected()){
        rd1_transfer_to_bankname.setSelected(false);
        }
    }//GEN-LAST:event_rd2_transfer_to_banknameActionPerformed

    private void rd1_transfer_from_banknameComponentAdded(java.awt.event.ContainerEvent evt) {//GEN-FIRST:event_rd1_transfer_from_banknameComponentAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_rd1_transfer_from_banknameComponentAdded

    private void rd1_transfer_from_banknameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rd1_transfer_from_banknameActionPerformed
        // TODO add your handling code here:
         if(rd1_transfer_from_bankname.isSelected()){
          rd2_transfer_from_bankname.setSelected(false);
        }
    }//GEN-LAST:event_rd1_transfer_from_banknameActionPerformed

    private void rd2_transfer_from_banknameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rd2_transfer_from_banknameActionPerformed
        // TODO add your handling code here:
         if(rd2_transfer_from_bankname.isSelected()){
        rd1_transfer_from_bankname.setSelected(false);
        }
    }//GEN-LAST:event_rd2_transfer_from_banknameActionPerformed

    private void from_tableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_from_tableMouseClicked
        // TODO add your handling code here:
         TableModel model=from_table.getModel();
        int row =from_table.getSelectedRow();
        String bankname=(String)model.getValueAt(row,0);
        rd2_transfer_from_bankname.setText(bankname);
        rd2_transfer_from_bankname.setSelected(true);
        rd1_transfer_from_bankname.setSelected(false);
    }//GEN-LAST:event_from_tableMouseClicked

    private void btnselfcontinueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnselfcontinueActionPerformed
        // TODO add your handling code here:
        
        if((rd1_transfer_from_bankname.isSelected() && rd2_transfer_to_bankname.isSelected()) || (rd2_transfer_from_bankname.isSelected() && rd1_transfer_to_bankname.isSelected())){           
           selfpanel.setVisible(true);
        }else{
            JOptionPane.showMessageDialog(null, "Pls Select Differnt \n Bank to Transfer");
             
        }
            
        
    }//GEN-LAST:event_btnselfcontinueActionPerformed

    private void txtselfamountFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtselfamountFocusGained
        // TODO add your handling code here:
        if(txtselfamount.getText().equals("Enter Amount")){
            txtselfamount.setText("");
            txtselfamount.setForeground(new Color(0, 0, 0));
        }
    }//GEN-LAST:event_txtselfamountFocusGained

    private void txtselfamountFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtselfamountFocusLost
        // TODO add your handling code here:
        if(txtselfamount.getText().equals("")){
            txtselfamount.setText("Enter Amount");
            txtselfamount.setForeground(new Color(153, 153, 153));
        }
    }//GEN-LAST:event_txtselfamountFocusLost

    private void selfpanelComponentAdded(java.awt.event.ContainerEvent evt) {//GEN-FIRST:event_selfpanelComponentAdded
        // TODO add your handling code here:
        selfpanel.setVisible(false);
    }//GEN-LAST:event_selfpanelComponentAdded

    private void btnselfpayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnselfpayActionPerformed
        // TODO add your handling code here:
        int selftransfer_amount = Integer.parseInt(txtselfamount.getText());
       
       int  parentamount = Integer.parseInt(amount);
       
       
       if(rd1_transfer_from_bankname.isSelected()){
            rembal = parentamount-selftransfer_amount;
       }else{
            rembal = parentamount+selftransfer_amount;
       }
       String rembalance = ""+rembal;
       
       //from added bank to default bank 
       String rd2name = rd2_transfer_from_bankname.getText();
        try{
           Class.forName("com.mysql.jdbc.Driver");
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/onbanking_system","root","");
            String sql = "select * from added_bank where Bank_Name='"+rd2name+"'";
            PreparedStatement pst = con.prepareStatement(sql);
            ResultSet rs = pst.executeQuery();
            while(rs.next()){
                 rd2amount  = Integer.parseInt(rs.getString("Amount"));
                 
            }
       }catch(Exception ex){
           System.out.println(ex.getMessage());
       }
       
       if(rd2_transfer_from_bankname.isSelected()){
           finalamount = rd2amount-selftransfer_amount;
       }else{
            finalamount = rd2amount+selftransfer_amount;
       }
       if(selftransfer_amount<rd2amount){
             try{
            Class.forName("com.mysql.jdbc.Driver");
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/onbanking_system","root","");
             String sql = "update added_bank set Amount='"+finalamount+"' where Bank_Name='"+rd2name+"'";
             PreparedStatement pst = con.prepareStatement(sql);
            int i=pst.executeUpdate();
            if(i>0){
            }
              Random rnd = new Random();
               int num = rnd.nextInt(999999);
              String transaction = String.format("%012d", num);
              
               String sql2 = "insert into transactions(Transaction_ID,Too,Fromm,Amount)values('"+transaction+"','"+sendername+"','"+rd2name+"','"+txtselfamount.getText()+"')";
                   PreparedStatement pst2 = con.prepareStatement(sql2);
                  int j=pst2.executeUpdate();
             
             if(j>0){
              //   JOptionPane.showMessageDialog(null,"Pay Succesfully");
                 
             }
              
           }catch(Exception ex){
              System.out.println(ex.getMessage());
           }
        }
       
        if(selftransfer_amount<parentamount){
             try{
            Class.forName("com.mysql.jdbc.Driver");
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/onbanking_system","root","");
             String sql = "update userdetails set Amount='"+rembalance+"' where username='"+pusername+"' and password='"+pass+"'";
             PreparedStatement pst = con.prepareStatement(sql);
            int i=pst.executeUpdate();
            if(i>0){
            }
              Random rnd = new Random();
               int num = rnd.nextInt(999999);
              String transaction = String.format("%012d", num);
              
               String sql2 = "insert into transactions(Transaction_ID,Too,Fromm,Amount)values('"+transaction+"','"+rd2name+"','"+sendername+"','"+txtselfamount.getText()+"')";
                   PreparedStatement pst2 = con.prepareStatement(sql2);
                  int j=pst2.executeUpdate();
             
             if(j>0){
                JOptionPane.showMessageDialog(null,"Pay Succesfully");
                 
             }
              
           }catch(Exception ex){
              System.out.println(ex.getMessage());
           }
        }
        
        
    }//GEN-LAST:event_btnselfpayActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        Login_Page lp = new Login_Page();
        lp.getCredential(pusername, pass);
        lp.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Self_Transfer_Page.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Self_Transfer_Page.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Self_Transfer_Page.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Self_Transfer_Page.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Self_Transfer_Page().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnselfcontinue;
    private javax.swing.JButton btnselfpay;
    private javax.swing.JTable from_table;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JLabel lbltransfer2;
    private javax.swing.JRadioButton rd1_transfer_from_bankname;
    private javax.swing.JRadioButton rd1_transfer_to_bankname;
    private javax.swing.JRadioButton rd2_transfer_from_bankname;
    private javax.swing.JRadioButton rd2_transfer_to_bankname;
    private javax.swing.JPanel selfpanel;
    private javax.swing.JTable to_table;
    private javax.swing.JTextField txtselfamount;
    // End of variables declaration//GEN-END:variables
}
