/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Online_Banking_System;

import javax.swing.JOptionPane;


/**
 *
 * @author subodh
 */
public class Send_Money_Page extends javax.swing.JFrame{

    /**
     * Creates new form user_page
     */
     String sendername,upiid,amount,pusername,pass,upitextamount;
    
     public void getData(String name,String balance,String username,String password){
         sendername = name;
         amount = balance;
         pusername = username;
         pass = password;
     }

    public Send_Money_Page() {
        initComponents();
    }
    
  

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnaddbank = new javax.swing.JButton();
        btnhistory = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        btnsendmoney = new javax.swing.JButton();
        btnviewbalance2 = new javax.swing.JButton();
        jSeparator2 = new javax.swing.JSeparator();
        bottom = new javax.swing.JLabel();
        profile_panel = new javax.swing.JPanel();
        btnprofile = new javax.swing.JButton();
        btnqueries = new javax.swing.JButton();
        btnlogout = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        sendmoneyarea = new javax.swing.JPanel();
        lbl_send_Money_heading = new javax.swing.JLabel();
        btn_sendmoney_close = new javax.swing.JButton();
        jSeparator3 = new javax.swing.JSeparator();
        btnupi = new javax.swing.JButton();
        btnbanktransfer = new javax.swing.JButton();
        btntoself = new javax.swing.JButton();
        lblbanktransfer = new javax.swing.JLabel();
        lblupi = new javax.swing.JLabel();
        lblbanktransfer1 = new javax.swing.JLabel();
        sendbottom = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocation(new java.awt.Point(350, 200));
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                formMouseClicked(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnaddbank.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        btnaddbank.setText("Add Bank Account");
        btnaddbank.setToolTipText("Add Bank Account\n");
        btnaddbank.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.darkGray, java.awt.Color.gray, java.awt.Color.red, java.awt.Color.black));
        btnaddbank.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnaddbankActionPerformed(evt);
            }
        });
        getContentPane().add(btnaddbank, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 70, 90, 50));

        btnhistory.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        btnhistory.setText("Transaction History"); // NOI18N
        btnhistory.setToolTipText("Transaction History");
        btnhistory.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED, java.awt.Color.darkGray, java.awt.Color.gray, java.awt.Color.red, java.awt.Color.black));
        btnhistory.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnhistory.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnhistoryActionPerformed(evt);
            }
        });
        getContentPane().add(btnhistory, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 70, 90, 50));

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/profile.jpg"))); // NOI18N
        jButton1.setBorderPainted(false);
        jButton1.setContentAreaFilled(false);
        jButton1.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                jButton1MouseMoved(evt);
            }
        });
        jButton1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jButton1FocusGained(evt);
            }
        });
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButton1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jButton1MouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jButton1MousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jButton1MouseReleased(evt);
            }
        });
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 0, 50, 50));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/bank (1).png"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 40, 40));

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Welcome to XYZ Bank");
        jLabel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 20, 130, 20));

        btnsendmoney.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        btnsendmoney.setText("Send Money");
        btnsendmoney.setToolTipText("Send Money\n");
        btnsendmoney.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.darkGray, java.awt.Color.gray, java.awt.Color.red, java.awt.Color.black));
        btnsendmoney.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsendmoneyActionPerformed(evt);
            }
        });
        getContentPane().add(btnsendmoney, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 70, 90, 50));

        btnviewbalance2.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        btnviewbalance2.setText("View Balance");
        btnviewbalance2.setToolTipText("View Balance");
        btnviewbalance2.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED, java.awt.Color.darkGray, java.awt.Color.gray, java.awt.Color.red, java.awt.Color.black));
        btnviewbalance2.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnviewbalance2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnviewbalance2ActionPerformed(evt);
            }
        });
        getContentPane().add(btnviewbalance2, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 70, 90, 50));
        getContentPane().add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 50, 650, 10));
        getContentPane().add(bottom, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 340, 40, 20));

        profile_panel.addContainerListener(new java.awt.event.ContainerAdapter() {
            public void componentAdded(java.awt.event.ContainerEvent evt) {
                profile_panelComponentAdded(evt);
            }
        });

        btnprofile.setText("Profile");
        btnprofile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnprofileActionPerformed(evt);
            }
        });

        btnqueries.setText("Queries");

        btnlogout.setText("Logout");
        btnlogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnlogoutActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout profile_panelLayout = new javax.swing.GroupLayout(profile_panel);
        profile_panel.setLayout(profile_panelLayout);
        profile_panelLayout.setHorizontalGroup(
            profile_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(profile_panelLayout.createSequentialGroup()
                .addGroup(profile_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, profile_panelLayout.createSequentialGroup()
                        .addGap(0, 1, Short.MAX_VALUE)
                        .addComponent(btnqueries))
                    .addComponent(btnprofile, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnlogout, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        profile_panelLayout.setVerticalGroup(
            profile_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(profile_panelLayout.createSequentialGroup()
                .addComponent(btnprofile)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnqueries)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnlogout)
                .addContainerGap(19, Short.MAX_VALUE))
        );

        getContentPane().add(profile_panel, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 60, 80, 100));
        getContentPane().add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 130, 650, -1));

        sendmoneyarea.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        sendmoneyarea.setEnabled(false);
        sendmoneyarea.addContainerListener(new java.awt.event.ContainerAdapter() {
            public void componentAdded(java.awt.event.ContainerEvent evt) {
                sendmoneyareaComponentAdded(evt);
            }
        });
        sendmoneyarea.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbl_send_Money_heading.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        lbl_send_Money_heading.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_send_Money_heading.setText("Send Money");
        sendmoneyarea.add(lbl_send_Money_heading, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 10, -1, -1));

        btn_sendmoney_close.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/close_1.png"))); // NOI18N
        btn_sendmoney_close.setBorder(null);
        btn_sendmoney_close.setBorderPainted(false);
        btn_sendmoney_close.setContentAreaFilled(false);
        btn_sendmoney_close.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_sendmoney_closeActionPerformed(evt);
            }
        });
        sendmoneyarea.add(btn_sendmoney_close, new org.netbeans.lib.awtextra.AbsoluteConstraints(365, 13, -1, -1));
        sendmoneyarea.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(2, 46, 396, -1));

        btnupi.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/upi (1).png"))); // NOI18N
        btnupi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnupiActionPerformed(evt);
            }
        });
        sendmoneyarea.add(btnupi, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 90, 70, 50));

        btnbanktransfer.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/bank (1).png"))); // NOI18N
        btnbanktransfer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnbanktransferActionPerformed(evt);
            }
        });
        sendmoneyarea.add(btnbanktransfer, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 90, 70, 50));

        btntoself.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/toself.png"))); // NOI18N
        btntoself.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btntoselfActionPerformed(evt);
            }
        });
        sendmoneyarea.add(btntoself, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 90, 70, 50));

        lblbanktransfer.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        lblbanktransfer.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblbanktransfer.setText("Self Transfer");
        sendmoneyarea.add(lblbanktransfer, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 160, 100, -1));

        lblupi.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        lblupi.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblupi.setText("UPI");
        sendmoneyarea.add(lblupi, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 160, 40, -1));

        lblbanktransfer1.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        lblbanktransfer1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblbanktransfer1.setText("Bank Transfer");
        sendmoneyarea.add(lblbanktransfer1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 160, 100, -1));

        getContentPane().add(sendmoneyarea, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 140, 400, 210));
        getContentPane().add(sendbottom, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 370, 40, 10));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
       
    }//GEN-LAST:event_jButton1ActionPerformed

    private void btnsendmoneyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsendmoneyActionPerformed
        // TODO add your handling code here:
        sendmoneyarea.setVisible(true);
    }//GEN-LAST:event_btnsendmoneyActionPerformed

    private void jButton1FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jButton1FocusGained
        // TODO add your handling code here:
      
    }//GEN-LAST:event_jButton1FocusGained

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        // TODO add your handling code here:
        profile_panel.setVisible(true);
       
    }//GEN-LAST:event_jButton1MouseClicked

    private void jButton1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseExited
        // TODO add your handling code here:
        
    }//GEN-LAST:event_jButton1MouseExited

    private void jButton1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1MouseEntered

    private void jButton1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MousePressed
        // TODO add your handling code here:
         profile_panel.setVisible(false);
         
    }//GEN-LAST:event_jButton1MousePressed

    private void jButton1MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseMoved
        // TODO add your handling code here:
        
    }//GEN-LAST:event_jButton1MouseMoved

    private void jButton1MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseReleased
        // TODO add your handling code here:
        
    }//GEN-LAST:event_jButton1MouseReleased

    private void formMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseClicked
        // TODO add your handling code here:
        profile_panel.setVisible(false);
        
    }//GEN-LAST:event_formMouseClicked

    private void profile_panelComponentAdded(java.awt.event.ContainerEvent evt) {//GEN-FIRST:event_profile_panelComponentAdded
        // TODO add your handling code here:
        profile_panel.setVisible(false);
    }//GEN-LAST:event_profile_panelComponentAdded

    private void btnlogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnlogoutActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnlogoutActionPerformed

    private void btnprofileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnprofileActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnprofileActionPerformed

    private void btn_sendmoney_closeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_sendmoney_closeActionPerformed
        // TODO add your handling code here:
       Login_Page lp = new Login_Page();
       lp.getCredential(pusername, pass);
        lp.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btn_sendmoney_closeActionPerformed

    private void sendmoneyareaComponentAdded(java.awt.event.ContainerEvent evt) {//GEN-FIRST:event_sendmoneyareaComponentAdded
        // TODO add your handling code here:
        
    }//GEN-LAST:event_sendmoneyareaComponentAdded

    private void btnviewbalance2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnviewbalance2ActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(null, "Please close \n below window first");
        
    }//GEN-LAST:event_btnviewbalance2ActionPerformed

    private void btntoselfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btntoselfActionPerformed
        // TODO add your handling code here:
        Self_Transfer_Page sp = new Self_Transfer_Page();
        sp.getData(sendername, amount, pusername, pass);
        sp.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btntoselfActionPerformed

    private void btnhistoryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnhistoryActionPerformed
        // TODO add your handling code here:
         JOptionPane.showMessageDialog(null, "Please close \n below window first");
    }//GEN-LAST:event_btnhistoryActionPerformed

    private void btnaddbankActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnaddbankActionPerformed
        // TODO add your handling code here:
         JOptionPane.showMessageDialog(null, "Please close \n below window first");
    }//GEN-LAST:event_btnaddbankActionPerformed

    private void btnupiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnupiActionPerformed
        // TODO add your handling code here:
        Pay_to_UPI ptu = new Pay_to_UPI();
        ptu.setVisible(true);
        ptu.getData(sendername, amount, pusername, pass);
        this.dispose();
    }//GEN-LAST:event_btnupiActionPerformed

    private void btnbanktransferActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnbanktransferActionPerformed
        // TODO add your handling code here:
        Bank_Transfer_Page bt = new Bank_Transfer_Page();
        bt.getData(sendername,amount,pusername,pass);
        bt.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnbanktransferActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Send_Money_Page.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Send_Money_Page.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Send_Money_Page.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Send_Money_Page.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Send_Money_Page().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel bottom;
    private javax.swing.JButton btn_sendmoney_close;
    private javax.swing.JButton btnaddbank;
    private javax.swing.JButton btnbanktransfer;
    private javax.swing.JButton btnhistory;
    private javax.swing.JButton btnlogout;
    private javax.swing.JButton btnprofile;
    private javax.swing.JButton btnqueries;
    private javax.swing.JButton btnsendmoney;
    private javax.swing.JButton btntoself;
    private javax.swing.JButton btnupi;
    private javax.swing.JButton btnviewbalance2;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JLabel lbl_send_Money_heading;
    private javax.swing.JLabel lblbanktransfer;
    private javax.swing.JLabel lblbanktransfer1;
    private javax.swing.JLabel lblupi;
    private javax.swing.JPanel profile_panel;
    private javax.swing.JLabel sendbottom;
    private javax.swing.JPanel sendmoneyarea;
    // End of variables declaration//GEN-END:variables
}
