/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Online_Banking_System;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.Random;
import javax.swing.JOptionPane;

/**
 *
 * @author subodh
 */
public class Signup_Form extends javax.swing.JFrame {

    /**
     * Creates new form Signup_Form
     */
    String gender="",dates;
    DateFormat formate;
    public Signup_Form() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        lblname = new javax.swing.JLabel();
        txtname = new javax.swing.JTextField();
        lblcreaterepassword = new javax.swing.JLabel();
        lblemail = new javax.swing.JLabel();
        lblmobile = new javax.swing.JLabel();
        lbladdress = new javax.swing.JLabel();
        lblcreateusername = new javax.swing.JLabel();
        lblcreatepassword = new javax.swing.JLabel();
        txtemail = new javax.swing.JTextField();
        txtmobile = new javax.swing.JTextField();
        txtaddress = new javax.swing.JTextField();
        txtuserusername = new javax.swing.JTextField();
        txtuserpassword = new javax.swing.JTextField();
        txtuserrepassword = new javax.swing.JPasswordField();
        btnsavesignup = new javax.swing.JButton();
        createacc = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        bottom = new javax.swing.JLabel();
        lblgender = new javax.swing.JLabel();
        rdmale = new javax.swing.JRadioButton();
        rdfemale = new javax.swing.JRadioButton();
        btnusergoback = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        lbldob = new javax.swing.JLabel();
        txtdob = new com.toedter.calendar.JDateChooser();
        lblamount = new javax.swing.JLabel();
        txtamount = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtbankname = new javax.swing.JTextField();
        lblifsccode = new javax.swing.JLabel();
        txtifsccode = new javax.swing.JTextField();
        lblactive = new javax.swing.JLabel();
        txtactivestatus = new javax.swing.JTextField();
        lblnote = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocation(new java.awt.Point(400, 50));
        setMaximumSize(new java.awt.Dimension(600, 600));
        setSize(new java.awt.Dimension(600, 600));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblname.setText("Name ");
        getContentPane().add(lblname, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 70, -1, -1));
        getContentPane().add(txtname, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 70, 150, -1));

        lblcreaterepassword.setText("re enter password");
        getContentPane().add(lblcreaterepassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 360, -1, -1));

        lblemail.setText("Email ");
        getContentPane().add(lblemail, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 110, -1, -1));

        lblmobile.setText("Mobile Number ");
        getContentPane().add(lblmobile, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 150, -1, 20));

        lbladdress.setText("Address");
        getContentPane().add(lbladdress, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 200, -1, -1));

        lblcreateusername.setText("username");
        getContentPane().add(lblcreateusername, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 280, -1, -1));

        lblcreatepassword.setText("Password");
        getContentPane().add(lblcreatepassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 320, -1, -1));

        txtemail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtemailActionPerformed(evt);
            }
        });
        getContentPane().add(txtemail, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 110, 150, -1));
        getContentPane().add(txtmobile, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 150, 150, -1));
        getContentPane().add(txtaddress, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 200, 150, -1));

        txtuserusername.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtuserusernameActionPerformed(evt);
            }
        });
        getContentPane().add(txtuserusername, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 270, 150, -1));

        txtuserpassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtuserpasswordActionPerformed(evt);
            }
        });
        getContentPane().add(txtuserpassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 310, 150, -1));

        txtuserrepassword.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtuserrepasswordFocusLost(evt);
            }
        });
        txtuserrepassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtuserrepasswordActionPerformed(evt);
            }
        });
        getContentPane().add(txtuserrepassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 350, 150, -1));

        btnsavesignup.setText("Submit");
        btnsavesignup.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsavesignupActionPerformed(evt);
            }
        });
        getContentPane().add(btnsavesignup, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 580, -1, -1));

        createacc.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        createacc.setText("Create Account");
        createacc.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        createacc.setOpaque(true);
        getContentPane().add(createacc, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 10, 90, 20));
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 160, 40, 30));
        getContentPane().add(bottom, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 620, 60, 10));

        lblgender.setText("Gender");
        getContentPane().add(lblgender, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 240, -1, -1));

        rdmale.setText("Male");
        rdmale.addContainerListener(new java.awt.event.ContainerAdapter() {
            public void componentAdded(java.awt.event.ContainerEvent evt) {
                rdmaleComponentAdded(evt);
            }
        });
        rdmale.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdmaleActionPerformed(evt);
            }
        });
        getContentPane().add(rdmale, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 240, -1, -1));

        rdfemale.setText("Female");
        rdfemale.addContainerListener(new java.awt.event.ContainerAdapter() {
            public void componentAdded(java.awt.event.ContainerEvent evt) {
                rdfemaleComponentAdded(evt);
            }
        });
        rdfemale.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdfemaleActionPerformed(evt);
            }
        });
        getContentPane().add(rdfemale, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 240, -1, -1));

        btnusergoback.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/icons8-go-back-30.png"))); // NOI18N
        btnusergoback.setContentAreaFilled(false);
        btnusergoback.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnusergobackActionPerformed(evt);
            }
        });
        getContentPane().add(btnusergoback, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 50, 30));
        getContentPane().add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 50, 540, 10));

        lbldob.setText("DOB");
        getContentPane().add(lbldob, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 390, -1, -1));
        getContentPane().add(txtdob, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 380, 150, -1));

        lblamount.setText("Opening Amount");
        getContentPane().add(lblamount, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 420, -1, -1));
        getContentPane().add(txtamount, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 420, 150, -1));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/bank (1).png"))); // NOI18N
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 10, 30, 40));

        jLabel2.setText("Bank Name");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 460, -1, -1));

        txtbankname.setText("XYZ Bank");
        txtbankname.setEnabled(false);
        getContentPane().add(txtbankname, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 460, 150, -1));

        lblifsccode.setText("IFSC CODE");
        getContentPane().add(lblifsccode, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 500, -1, -1));

        txtifsccode.setText("XYZ123");
        txtifsccode.setEnabled(false);
        getContentPane().add(txtifsccode, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 500, 150, -1));

        lblactive.setText("Active Status");
        getContentPane().add(lblactive, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 540, -1, -1));

        txtactivestatus.setText("NO");
        txtactivestatus.setEnabled(false);
        txtactivestatus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtactivestatusActionPerformed(evt);
            }
        });
        getContentPane().add(txtactivestatus, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 540, 50, -1));

        lblnote.setForeground(new java.awt.Color(255, 51, 51));
        lblnote.setText("note:- once it verify by admin u will able to login");
        getContentPane().add(lblnote, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 540, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtemailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtemailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtemailActionPerformed

    private void rdmaleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdmaleActionPerformed
        // TODO add your handling code here:
        gender = "Male";
        rdfemale.setSelected(false);
    }//GEN-LAST:event_rdmaleActionPerformed

    private void rdmaleComponentAdded(java.awt.event.ContainerEvent evt) {//GEN-FIRST:event_rdmaleComponentAdded
        // TODO add your handling code here:
        
        
        buttonGroup1.add(rdmale);
       
    }//GEN-LAST:event_rdmaleComponentAdded

    private void rdfemaleComponentAdded(java.awt.event.ContainerEvent evt) {//GEN-FIRST:event_rdfemaleComponentAdded
        // TODO add your handling code here:
       
        buttonGroup1.add(rdfemale);
        
    }//GEN-LAST:event_rdfemaleComponentAdded

    private void rdfemaleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdfemaleActionPerformed
        // TODO add your handling code here:
        gender="Female";
        rdmale.setSelected(false);
    }//GEN-LAST:event_rdfemaleActionPerformed

    private void txtuserusernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtuserusernameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtuserusernameActionPerformed

    private void txtuserpasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtuserpasswordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtuserpasswordActionPerformed

    private void btnusergobackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnusergobackActionPerformed
        // TODO add your handling code here:
        Login_Page lp1 = new Login_Page();
        lp1.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnusergobackActionPerformed

    private void btnsavesignupActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsavesignupActionPerformed
        // TODO add your handling code here:
         Date date = txtdob.getDate();
        formate = new SimpleDateFormat("dd/MM/yyyy");
        dates = formate.format(date);
        
        	 Random rnd = new Random();
                int number = rnd.nextInt(999999);
                String accno = String.format("%012d", number);
        
        String prevpass = txtuserpassword.getText();
        String pass =new String (txtuserrepassword.getPassword());
        if(prevpass.equals(pass)){
            try{
                Class.forName("com.mysql.jdbc.Driver");
                Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/onbanking_system","root","");
                String sql = "insert into userdetails(uname,uemail,umobile,uaddress,ugender,DOB,username,password,BankName,IFSCCode,AccountNumber,ActiveStatus,Amount) values('"+txtname.getText()+"','"+txtemail.getText()+"','"+txtmobile.getText()+"','"+txtaddress.getText()+"','"+gender+"','"+dates+"','"+txtuserusername.getText()+"','"+pass+"','"+txtbankname.getText()+"','"+txtifsccode.getText()+"','"+accno+"','"+txtactivestatus.getText()+"','"+txtamount.getText()+"')";
                
             PreparedStatement pst = con.prepareStatement(sql);
             int i=pst.executeUpdate();
             
             if(i>0){
                 JOptionPane.showMessageDialog(null, "Account Created \n Wait until it verify ");
             }
                
            }catch(Exception ex){
                System.out.println(ex.getMessage());
            }
            
        }else{
            JOptionPane.showMessageDialog(null, "password not match");
        }
    }//GEN-LAST:event_btnsavesignupActionPerformed

    private void txtuserrepasswordFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtuserrepasswordFocusLost
        // TODO add your handling code here:
          String prevpass = txtuserpassword.getText();
        String pass =new String (txtuserrepassword.getPassword());
        if(prevpass.equals(pass)){
            
        }else{
            JOptionPane.showMessageDialog(null, "password not match");
        }
    }//GEN-LAST:event_txtuserrepasswordFocusLost

    private void txtactivestatusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtactivestatusActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtactivestatusActionPerformed

    private void txtuserrepasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtuserrepasswordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtuserrepasswordActionPerformed

       /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Signup_Form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Signup_Form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Signup_Form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Signup_Form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Signup_Form().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel bottom;
    private javax.swing.JButton btnsavesignup;
    private javax.swing.JButton btnusergoback;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel createacc;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel lblactive;
    private javax.swing.JLabel lbladdress;
    private javax.swing.JLabel lblamount;
    private javax.swing.JLabel lblcreatepassword;
    private javax.swing.JLabel lblcreaterepassword;
    private javax.swing.JLabel lblcreateusername;
    private javax.swing.JLabel lbldob;
    private javax.swing.JLabel lblemail;
    private javax.swing.JLabel lblgender;
    private javax.swing.JLabel lblifsccode;
    private javax.swing.JLabel lblmobile;
    private javax.swing.JLabel lblname;
    private javax.swing.JLabel lblnote;
    private javax.swing.JRadioButton rdfemale;
    private javax.swing.JRadioButton rdmale;
    private javax.swing.JTextField txtactivestatus;
    private javax.swing.JTextField txtaddress;
    private javax.swing.JTextField txtamount;
    private javax.swing.JTextField txtbankname;
    private com.toedter.calendar.JDateChooser txtdob;
    private javax.swing.JTextField txtemail;
    private javax.swing.JTextField txtifsccode;
    private javax.swing.JTextField txtmobile;
    private javax.swing.JTextField txtname;
    private javax.swing.JTextField txtuserpassword;
    private javax.swing.JPasswordField txtuserrepassword;
    private javax.swing.JTextField txtuserusername;
    // End of variables declaration//GEN-END:variables
}
