/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Online_Banking_System;

import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.print.PageFormat;
import java.awt.print.Printable;
import java.awt.print.PrinterException;
import java.awt.print.PrinterJob;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.TableModel;
import net.proteanit.sql.DbUtils;

/**
 *
 * @author subodh
 */
public class Transaction_Page extends javax.swing.JFrame {

    /**
     * Creates new form Transaction_Page
     */
    String username,password,email;
    
     String sendername,upiid,amount,pusername,pass,upitextamount;
    
     public void getData(String name,String balance,String username,String password){
         sendername = name;
         amount = balance;
         pusername = username;
         pass = password;
     }

     public void getEmail(String email){
         this.email = email;
     }
    public Transaction_Page() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbltransaction = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        btngoback = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        thtable = new javax.swing.JTable();
        btnprint = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocation(new java.awt.Point(350, 200));
        addWindowFocusListener(new java.awt.event.WindowFocusListener() {
            public void windowGainedFocus(java.awt.event.WindowEvent evt) {
                formWindowGainedFocus(evt);
            }
            public void windowLostFocus(java.awt.event.WindowEvent evt) {
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbltransaction.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        lbltransaction.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbltransaction.setText("Transaction History");
        lbltransaction.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        getContentPane().add(lbltransaction, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 10, -1, 20));
        getContentPane().add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, 600, 10));

        btngoback.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/icons8-go-back-30.png"))); // NOI18N
        btngoback.setBorderPainted(false);
        btngoback.setContentAreaFilled(false);
        btngoback.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btngobackActionPerformed(evt);
            }
        });
        getContentPane().add(btngoback, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 30, 30));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/history_new.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 10, -1, -1));

        thtable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        thtable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                thtableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(thtable);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, 580, 160));

        btnprint.setForeground(new java.awt.Color(204, 0, 0));
        btnprint.setText("Print");
        btnprint.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnprintActionPerformed(evt);
            }
        });
        getContentPane().add(btnprint, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 250, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowGainedFocus(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowGainedFocus
        // TODO add your handling code here:
          try{
            Class.forName("com.mysql.jdbc.Driver");
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/onbanking_system","root","");
            String sql = "Select * from transactions";
            PreparedStatement pst = con.prepareCall(sql);
            ResultSet rs = pst.executeQuery();
            thtable.setModel(DbUtils.resultSetToTableModel(rs));
            
            
          TableModel model=thtable.getModel();
//          thtable.setBackground(java.awt.Color.red);
         int row =thtable.getSelectedRow();
         int srno=(int)model.getValueAt(1,0);
              
        
        
            
        }catch(Exception ex){
            
        }
    }//GEN-LAST:event_formWindowGainedFocus

    private void thtableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_thtableMouseClicked
        // TODO add your handling code here:
         TableModel model=thtable.getModel();
        int row =thtable.getSelectedRow();
        int id=(int)model.getValueAt(row,0);
        String tn = (String)model.getValueAt(row, 1);
        JOptionPane.showMessageDialog(null,"id:"+id+"\n"+"Transaction No."+tn);
    }//GEN-LAST:event_thtableMouseClicked

    private void btngobackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btngobackActionPerformed
        // TODO add your handling code here:
        user_page up = new user_page();
        up.setVisible(true);
        up.getData(sendername, amount, username, password);
                
                up.getEmail(email);
        
        this.dispose();
    }//GEN-LAST:event_btngobackActionPerformed

    private void btnprintActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnprintActionPerformed
        try {
            // TODO add your handling code here:
            thtable.print();
        } catch (PrinterException ex) {
            System.out.println(ex.getMessage());
        }
  
    }//GEN-LAST:event_btnprintActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Transaction_Page.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Transaction_Page.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Transaction_Page.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Transaction_Page.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Transaction_Page().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btngoback;
    private javax.swing.JButton btnprint;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel lbltransaction;
    private javax.swing.JTable thtable;
    // End of variables declaration//GEN-END:variables
}
